# Generated by Django 4.0 on 2021-12-09 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.topico'),
        ),
    ]
